name: Crystal Test

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  crystal_test:
    name: Crystal Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal-version: ["1.9", "1.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal-version }}

      - name: Install dependencies
        run: shards install

      - name: Run specs
        run: crystal spec
