name: Crystal Test

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  crystal_test:
    name: Crystal Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: crystal_pg_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        crystal-version: ["1.9", "1.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal-version }}

      - name: Install dependencies
        run: shards install

      - name: Run specs
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/crystal_pg_test
        run: crystal spec
